image: gcc

before_script:
- export PATH="wine-stable/bin${PATH:+:$PATH}"

install:wine:
  stage: build
  cache:
    key: wine
    paths:
    - wine-stable
  artifacts:
    expire_in: 1 hour
    paths:
    - wine-stable
  script:
  - |
    if [ ! -x wine-stable/bin/winegcc ]; then
      mkdir -p wine-stable
      wget -O wine-i386.deb https://dl.winehq.org/wine-builds/debian/pool/main/wine-stable-i386_3.0.1~jessie_i386.deb
      wget -O wine-amd64.deb https://dl.winehq.org/wine-builds/debian/pool/main/wine-stable-amd64_3.0.1~jessie_amd64.deb
      wget -O wine-dev.deb https://dl.winehq.org/wine-builds/debian/pool/main/wine-stable-dev_3.0.1~jessie_i386.deb
      dpkg -X wine-i386.deb wine-stable
      dpkg -X wine-amd64.deb wine-stable
      dpkg -X wine-dev.deb wine-stable
      mv wine-stable/opt/winestable/* wine-stable
      rm -rf wine-stable/opt wine-stable/usr
    fi

build:compiler:
  stage: build
  cache:
    key: nim-compiler
    paths:
    - nim-devel
    - nim-master
  artifacts:
    expire_in: 1h
    paths:
    - nim-master/bin
    - nim-master/config
    - nim-master/lib
    - nim-devel/bin
    - nim-devel/config
    - nim-devel/lib
  script:
  - |
    for BRANCH in master devel; do
    if [ ! -x nim-$BRANCH/bin/nim ]; then
      git clone -b $BRANCH --depth 1 git://github.com/nim-lang/nim nim-$BRANCH/
      cd nim-$BRANCH
      git clone --depth 1 git://github.com/nim-lang/csources csources/
      cd csources
      sh build.sh
      cd ..
      rm -rf csources
      bin/nim c koch
      ./koch boot -d:release
      ./koch nimble
    else
      cd nim-$BRANCH
      git fetch origin
      if ! git merge FETCH_HEAD | grep "Already up-to-date"; then
        bin/nim c koch
        ./koch boot -d:release
        ./koch nimble
      fi
    fi
    cd ..
    done


test:master:
  stage: test
  dependencies:
  - build:compiler
  - install:wine
  script:
  - nim-master/bin/nim -v
  - winegcc -v
  - wine --version
  - make NIMC="$PWD/nim-master/bin/nim" ARCH=64 precompile

test:devel:
  stage: test
  dependencies:
  - build:compiler
  - install:wine
  allow_failure: true
  script:
  - nim-devel/bin/nim -v
  - winegcc -v
  - wine --version
  - make NIMC="$PWD/nim-devel/bin/nim" ARCH=64 precompile
