sudo: required
services:
  - docker
env:
  # Build and test against the master and devel branches of Nim
  - BRANCH=master
  - BRANCH=devel
matrix:
  allow_failures:
    # Ignore failures when building against the devel Nim branch
    - env: BRANCH=devel
  fast_finish: true
before_install:
  - docker pull nimlang/nim:$BRANCH
script:
  - docker run nimlang/nim nim --version
  - docker run --rm -v "$(pwd):/usr/src/app" -w /usr/src/app nimlang/nim:$BRANCH make tools
  - docker run --rm -v "$(pwd):/usr/src/app" -w /usr/src/app nimlang/nim:$BRANCH make tests
branches:
  except:
    - gh-pages
